name: CI pipeline

on: push


jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install dependencies
        run: |
          pip install -r requirements.txt
      - name: run pipeline for docker
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro

      - name: Run model tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote the new model to production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python scripts/promote_model.py

      - name: Run flask app tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python -m unittest tests/test_flask_app.py

# Uncomment the following lines to enable deployment to Docker Hub and EC2 but 
# then comment ECR To EC2 section code written below
      # - name: Login to Docker Hub
      #   if: success()
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Build docker image
      #   if: success()
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/model1.10:latest .
      # - name: Push docker image to Docker Hub

      #   if: success()
      #   run: |
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/model1.10:latest 
           
      # - name : Deploy to EC2 
      #   if: success()
      #   uses: appleboy/ssh-action@v0.1.5
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       docker pull ${{secrets.DOCKER_HUB_USERNAME}}/model1.10:latest
      #       docker stop my-app || true
      #       docker rm my-app || true
      #       docker run -d --name my-app -p 80:5000  \
      #       -e DAGSHUB_PAT=${{secrets.DAGSHUB_PAT}} \
      #       ${{secrets.DOCKER_HUB_USERNAME}}/model1.10:latest

# Below code is for deployment from ECR To EC2

      - name : Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 983499853713.dkr.ecr.us-east-2.amazonaws.com
      - name : Build Docker Image
        run: |
          docker build -t campusxecr .
      - name: Tag Docker Image
        run: |
          docker tag campusxecr:latest 983499853713.dkr.ecr.us-east-2.amazonaws.com/campusxecr:latest
      - name : Push Docker Image to ECR
        run: |
          docker push 983499853713.dkr.ecr.us-east-2.amazonaws.com/campusxecr:latest